### ISSUE TITLE
Make Whole Repository Importable in Android Studio

### ISSUE THREAD

**Issue by eugenkiss** [zserge/anvil-examples#1]
A feature request. It would be much more convenient to check out all the samples in this repository if the repository itself would be an Android module and the samples submodules. This way one could simply import the whole repository into Android Studio and selectively run the desired sample. Currently, if I'm not mistaken, I'd need to import each sample separately into Android Studio.

By the way, I also noticed that no gradle wrapper is committed for the sample projects.

**Comment by zserge** [comment]
Ah, yes. Thanks for letting me know. I personally don't use Android Studio at all (I do all my android development in vim+tmux which feels very smooth with java8/kotlin). So I didn't even know this problem exists.

I'm not sure how exactly to help you, but I've just pushed `settings.gradle` with list of subprojects included. I'm able to do, say, `gradle counter:installDebug` to install counter demo app from the root of the repo. I've also generated the wrappers for Gradle 2.7 (the one i'm using locally, which is a stable version).

Please let me know if this helps you to work with Android Studio, or if there is anything else I could do to resolve this?

**Comment by eugenkiss** [comment]
Thanks for your quick response and action. I'll take a look tomorrow and if it's not already working I'm going to change the project myself and submit a pull request.

**Comment by eugenkiss** [comment]
I tried it and it works now :+1: !

I don't want to create a separate issue for this but [here](https://drive.google.com/file/d/0B5TCL7KHQEmrcFQxM0VuRUVmOGs/view?usp=sharing) is a video of the todo example running in a Lollipop Genymotion emulator. The behavior seems buggy.

**Comment by zserge** [comment]
Is it Java8, Kotlin, or Java6 variant of the Todo app?

May I suggest adding `mTodoAdapter.notifyDataSetChanged()` at the beginning of the view() function? I used it in Java 8 variant, but forgot about it in Java6 and Kotlin. If that's the case - feel free to make a pull request.

**Comment by eugenkiss** [comment]
Done: https://github.com/zserge/anvil-examples/pull/2
